Bugfix
Add `error=TRUE` so this known error doesn't stop rendering.
```
Quitting from lines 531-533 (transform.Rmd)
Error: Can't subset columns that don't exist.
✖ Column `variable_not_in_the_dataframe` doesn't exist.
```