Bugfix
fixes https://travis-ci.org/github/jrnold/r4ds-exercise-solutions/builds/705457081
```
Quitting from lines 563-564 (transform.Rmd)
Error: Can't subset columns that don't exist.
✖ Column `year` doesn't exist.
```